name: CI Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: Install dependencies
        run: |
          echo "No dependencies to install for basic test"

      - name: Run a test script
        run: |
          echo "Testing GitHub Actions Workflow"
<<<<<<< HEAD
          python -c "print('GitHub Actions is running correctly!')"
=======
          python -c "print('GitHub Actions is running correctly!')"
>>>>>>> 85f88b8d08a9978ad6a1befd078f6c87d2ac1c43
